// Banque de questions QCM (4 propositions) avec explication de la réponse.
// Volontairement "pas trop dures" — culture générale grand public.
export interface QcmQuestion {
  text: string;
  choices: string[]; // toujours 4 propositions
  correct: number; // index de la bonne réponse (0-3)
  category: string;
  explanation: string;
}

export const QCM_QUESTIONS: QcmQuestion[] = [
  { text: "Quelle est la capitale de la France ?", choices: ["Lyon", "Marseille", "Paris", "Lille"], correct: 2, category: "Géographie", explanation: "Paris est la capitale de la France." },
  { text: "Combien de planètes compte le système solaire ?", choices: ["7", "8", "9", "10"], correct: 1, category: "Sciences", explanation: "8, depuis que Pluton est passée en planète naine en 2006." },
  { text: "Quel est le plus grand océan du monde ?", choices: ["Atlantique", "Indien", "Arctique", "Pacifique"], correct: 3, category: "Géographie", explanation: "Le Pacifique couvre environ un tiers du globe." },
  { text: "Quelle planète est surnommée la planète rouge ?", choices: ["Vénus", "Mars", "Jupiter", "Saturne"], correct: 1, category: "Sciences", explanation: "Mars, à cause de l'oxyde de fer (la rouille) sur son sol." },
  { text: "Combien de côtés a un hexagone ?", choices: ["5", "6", "7", "8"], correct: 1, category: "Logique", explanation: "« Hexa » veut dire six." },
  { text: "Quel fleuve traverse Paris ?", choices: ["La Loire", "Le Rhône", "La Seine", "La Garonne"], correct: 2, category: "Géographie", explanation: "La Seine traverse Paris d'est en ouest." },
  { text: "Quelle est la formule chimique de l'eau ?", choices: ["CO2", "O2", "H2O", "NaCl"], correct: 2, category: "Sciences", explanation: "Deux atomes d'hydrogène et un d'oxygène." },
  { text: "Combien de joueurs dans une équipe de football ?", choices: ["9", "10", "11", "12"], correct: 2, category: "Sport", explanation: "11 joueurs, gardien compris." },
  { text: "Combien de lettres compte l'alphabet français ?", choices: ["24", "25", "26", "27"], correct: 2, category: "Culture", explanation: "26 lettres, de A à Z." },
  { text: "Quelle ville est surnommée la Ville Lumière ?", choices: ["Londres", "Paris", "Rome", "Venise"], correct: 1, category: "Culture", explanation: "Paris, pour son rayonnement et son éclairage précoce." },
  { text: "Quelle est la capitale de l'Italie ?", choices: ["Milan", "Venise", "Rome", "Naples"], correct: 2, category: "Géographie", explanation: "Rome, capitale depuis 1871." },
  { text: "Quelle est la capitale de l'Espagne ?", choices: ["Barcelone", "Madrid", "Séville", "Valence"], correct: 1, category: "Géographie", explanation: "Madrid, plus grande ville du pays." },
  { text: "Quelle est la capitale de l'Australie ?", choices: ["Sydney", "Melbourne", "Canberra", "Perth"], correct: 2, category: "Géographie", explanation: "Canberra, choisie comme compromis entre Sydney et Melbourne." },
  { text: "Quel est le plus haut sommet du monde ?", choices: ["Mont Blanc", "K2", "Everest", "Kilimandjaro"], correct: 2, category: "Géographie", explanation: "L'Everest culmine à 8 849 m." },
  { text: "Quel est le plus petit pays du monde ?", choices: ["Monaco", "Vatican", "Nauru", "Malte"], correct: 1, category: "Géographie", explanation: "Le Vatican, 0,44 km²." },
  { text: "Combien y a-t-il de continents ?", choices: ["5", "6", "7", "8"], correct: 2, category: "Géographie", explanation: "On en compte 7 dans le modèle courant." },
  { text: "Quel est l'animal terrestre le plus rapide ?", choices: ["Lion", "Guépard", "Antilope", "Cheval"], correct: 1, category: "Animaux", explanation: "Le guépard atteint environ 110 km/h." },
  { text: "Quel animal est le symbole de la marque Lacoste ?", choices: ["Alligator", "Crocodile", "Lézard", "Caïman"], correct: 1, category: "Culture", explanation: "Le crocodile, surnom du fondateur René Lacoste." },
  { text: "Quel est le plus grand désert chaud du monde ?", choices: ["Gobi", "Kalahari", "Sahara", "Atacama"], correct: 2, category: "Géographie", explanation: "Le Sahara, environ 9 millions de km²." },
  { text: "Quel est le pays le plus vaste du monde ?", choices: ["Chine", "Canada", "États-Unis", "Russie"], correct: 3, category: "Géographie", explanation: "La Russie, environ 17 millions de km²." },
  { text: "Qui a peint la Joconde ?", choices: ["Michel-Ange", "Léonard de Vinci", "Raphaël", "Botticelli"], correct: 1, category: "Art", explanation: "Léonard de Vinci, vers 1503-1519." },
  { text: "Qui a écrit Les Misérables ?", choices: ["Zola", "Hugo", "Balzac", "Flaubert"], correct: 1, category: "Culture", explanation: "Victor Hugo, publié en 1862." },
  { text: "Qui a réalisé le film Inception ?", choices: ["Spielberg", "Nolan", "Cameron", "Scorsese"], correct: 1, category: "Cinéma", explanation: "Christopher Nolan, en 2010." },
  { text: "Quel groupe a chanté Bohemian Rhapsody ?", choices: ["The Beatles", "Queen", "Pink Floyd", "U2"], correct: 1, category: "Musique", explanation: "Queen, sur l'album A Night at the Opera (1975)." },
  { text: "Quelle est la monnaie du Japon ?", choices: ["Yuan", "Won", "Yen", "Baht"], correct: 2, category: "Géographie", explanation: "Le yen." },
  { text: "Quelle est la monnaie du Royaume-Uni ?", choices: ["Euro", "Dollar", "Livre sterling", "Franc"], correct: 2, category: "Géographie", explanation: "La livre sterling." },
  { text: "En quelle année l'homme a-t-il marché sur la Lune ?", choices: ["1965", "1969", "1972", "1959"], correct: 1, category: "Histoire", explanation: "Apollo 11, le 20 juillet 1969." },
  { text: "En quelle année a eu lieu la Révolution française ?", choices: ["1776", "1789", "1799", "1815"], correct: 1, category: "Histoire", explanation: "1789, prise de la Bastille le 14 juillet." },
  { text: "Quand est tombé le mur de Berlin ?", choices: ["1985", "1989", "1991", "1993"], correct: 1, category: "Histoire", explanation: "Le 9 novembre 1989." },
  { text: "Combien d'os possède le corps humain adulte ?", choices: ["186", "206", "226", "246"], correct: 1, category: "Corps humain", explanation: "206 os chez l'adulte." },
  { text: "Combien de dents possède un adulte ?", choices: ["28", "30", "32", "34"], correct: 2, category: "Corps humain", explanation: "32 dents, dents de sagesse comprises." },
  { text: "Quel organe pompe le sang dans le corps ?", choices: ["Le foie", "Le cœur", "Le poumon", "Le rein"], correct: 1, category: "Corps humain", explanation: "Le cœur." },
  { text: "Quel est le symbole chimique de l'or ?", choices: ["Or", "Au", "Ag", "Fe"], correct: 1, category: "Sciences", explanation: "Au, du latin aurum." },
  { text: "Quel gaz est majoritaire dans l'air que l'on respire ?", choices: ["Oxygène", "Azote", "Dioxyde de carbone", "Hydrogène"], correct: 1, category: "Sciences", explanation: "L'azote, environ 78 % de l'atmosphère." },
  { text: "Quel est le plus grand mammifère du monde ?", choices: ["Éléphant", "Baleine bleue", "Girafe", "Cachalot"], correct: 1, category: "Animaux", explanation: "La baleine bleue, jusqu'à 30 m." },
  { text: "Combien de pattes a une araignée ?", choices: ["6", "8", "10", "12"], correct: 1, category: "Animaux", explanation: "8 pattes : ce n'est pas un insecte." },
  { text: "Combien de pattes a un insecte ?", choices: ["4", "6", "8", "10"], correct: 1, category: "Animaux", explanation: "6 pattes." },
  { text: "Quelle est la langue avec le plus de locuteurs natifs ?", choices: ["Anglais", "Espagnol", "Mandarin", "Hindi"], correct: 2, category: "Culture", explanation: "Le mandarin." },
  { text: "Quel pays a gagné la Coupe du Monde de foot 2018 ?", choices: ["Croatie", "France", "Brésil", "Allemagne"], correct: 1, category: "Sport", explanation: "La France, en Russie." },
  { text: "Quel pays a gagné la Coupe du Monde de foot 2022 ?", choices: ["France", "Argentine", "Brésil", "Maroc"], correct: 1, category: "Sport", explanation: "L'Argentine, aux tirs au but face à la France." },
  { text: "Combien de joueurs dans une équipe de rugby à XV ?", choices: ["11", "13", "15", "18"], correct: 2, category: "Sport", explanation: "15 joueurs." },
  { text: "Combien de cartes dans un jeu classique (sans jokers) ?", choices: ["48", "52", "54", "56"], correct: 1, category: "Culture", explanation: "52 cartes." },
  { text: "Combien de cases compte un échiquier ?", choices: ["36", "49", "64", "81"], correct: 2, category: "Logique", explanation: "64 cases (8 x 8)." },
  { text: "Quelle est la planète la plus proche du Soleil ?", choices: ["Vénus", "Mercure", "Mars", "La Terre"], correct: 1, category: "Sciences", explanation: "Mercure." },
  { text: "Autour de quel astre tourne la Terre ?", choices: ["La Lune", "Le Soleil", "Mars", "Jupiter"], correct: 1, category: "Sciences", explanation: "Le Soleil." },
  { text: "Combien de temps met la Terre à faire le tour du Soleil ?", choices: ["1 mois", "1 jour", "1 an", "10 ans"], correct: 2, category: "Sciences", explanation: "Environ 365 jours, soit un an." },
  { text: "Quelle couleur obtient-on en mélangeant le bleu et le jaune ?", choices: ["Vert", "Orange", "Violet", "Marron"], correct: 0, category: "Logique", explanation: "Le vert." },
  { text: "Quelle couleur obtient-on en mélangeant le rouge et le bleu ?", choices: ["Vert", "Orange", "Violet", "Gris"], correct: 2, category: "Logique", explanation: "Le violet." },
  { text: "Combien de minutes dans une heure ?", choices: ["50", "60", "90", "100"], correct: 1, category: "Logique", explanation: "60 minutes." },
  { text: "Combien de jours a février lors d'une année bissextile ?", choices: ["27", "28", "29", "30"], correct: 2, category: "Logique", explanation: "29 jours." },
  { text: "Quelle est la capitale des États-Unis ?", choices: ["New York", "Washington D.C.", "Los Angeles", "Chicago"], correct: 1, category: "Géographie", explanation: "Washington D.C." },
  { text: "Quelle est la capitale de l'Allemagne ?", choices: ["Munich", "Francfort", "Berlin", "Hambourg"], correct: 2, category: "Géographie", explanation: "Berlin." },
  { text: "Quelle est la capitale du Royaume-Uni ?", choices: ["Manchester", "Londres", "Liverpool", "Édimbourg"], correct: 1, category: "Géographie", explanation: "Londres." },
  { text: "Quel océan borde la côte ouest de la France ?", choices: ["La Méditerranée", "Le Pacifique", "L'Atlantique", "La mer du Nord"], correct: 2, category: "Géographie", explanation: "L'océan Atlantique." },
  { text: "Combien de couleurs compte un arc-en-ciel ?", choices: ["5", "6", "7", "8"], correct: 2, category: "Sciences", explanation: "7 couleurs traditionnellement." },
  { text: "Quel métal est liquide à température ambiante ?", choices: ["Le fer", "Le mercure", "Le plomb", "L'étain"], correct: 1, category: "Sciences", explanation: "Le mercure." },
  { text: "Qui a élaboré la théorie de la relativité ?", choices: ["Newton", "Einstein", "Galilée", "Hawking"], correct: 1, category: "Sciences", explanation: "Albert Einstein." },
  { text: "Quel instrument a 88 touches ?", choices: ["La guitare", "Le piano", "Le violon", "La harpe"], correct: 1, category: "Musique", explanation: "Le piano." },
  { text: "Combien de cordes a une guitare classique ?", choices: ["4", "5", "6", "7"], correct: 2, category: "Musique", explanation: "6 cordes." },
  { text: "Quel artiste a peint La Nuit étoilée ?", choices: ["Monet", "Van Gogh", "Picasso", "Dalí"], correct: 1, category: "Art", explanation: "Vincent van Gogh, en 1889." },
  { text: "Quel est le plus grand pays d'Afrique ?", choices: ["Nigeria", "Algérie", "Égypte", "Soudan"], correct: 1, category: "Géographie", explanation: "L'Algérie." },
  { text: "Quel est le plus long fleuve du monde ?", choices: ["L'Amazone", "Le Nil", "Le Mississippi", "Le Yangtsé"], correct: 1, category: "Géographie", explanation: "Le Nil (environ 6 650 km)." },
  { text: "Quel sport pratique-t-on à Roland-Garros ?", choices: ["Le golf", "Le tennis", "Le cyclisme", "Le rugby"], correct: 1, category: "Sport", explanation: "Le tennis, sur terre battue." },
  { text: "Quelle est la capitale du Portugal ?", choices: ["Porto", "Lisbonne", "Faro", "Braga"], correct: 1, category: "Géographie", explanation: "Lisbonne." },
  { text: "Combien de cordes a un violon ?", choices: ["3", "4", "5", "6"], correct: 1, category: "Musique", explanation: "4 cordes." },
  { text: "Quel est le symbole chimique du sodium ?", choices: ["So", "Na", "Sd", "S"], correct: 1, category: "Sciences", explanation: "Na, du latin natrium." },
  { text: "Quelle est la plus grande planète du système solaire ?", choices: ["Saturne", "Jupiter", "Neptune", "La Terre"], correct: 1, category: "Sciences", explanation: "Jupiter, une géante gazeuse." },
];
