import type { GameMeta } from "./types";

export const GAMES: GameMeta[] = [
  // -- Mots --
  {
    id: "bomb-party",
    name: "Bomb Party",
    description: "Trouve un mot contenant la syllabe imposee avant que la bombe explose !",
    category: "words",
    minPlayers: 2,
    maxPlayers: 8,
    icon: "💣",
    implemented: true,
    rules: [
      "Une syllabe est imposee a chaque tour",
      "Tape un mot contenant cette syllabe avant que le timer explose",
      "Chaque mot ne peut etre utilise qu'une seule fois",
      "Tu perds une vie si le temps expire",
      "Le dernier survivant gagne !",
    ],
    component: () => import("@/components/games/bomb-party/bomb-party-game"),
  },
  {
    id: "word-chain",
    name: "Chaine de mots",
    description: "Chaque joueur doit dire un mot commencant par la derniere lettre du mot precedent.",
    category: "words",
    minPlayers: 2,
    maxPlayers: 8,
    icon: "🔗",
    implemented: true,
    rules: [
      "Dis un mot commencant par la derniere lettre du mot precedent",
      "Le mot doit faire au moins 3 lettres",
      "Les mots deja utilises sont interdits",
      "Tu as 8 secondes par tour (diminue progressivement)",
      "3 vies - le dernier debout gagne",
    ],
    component: () => import("@/components/games/word-chain/word-chain-game"),
  },
  // -- Culture --
  {
    id: "speed-quiz",
    name: "Speed Quiz",
    description: "Reponds le plus vite possible aux questions de culture generale !",
    category: "trivia",
    minPlayers: 2,
    maxPlayers: 8,
    icon: "⚡",
    implemented: true,
    rules: [
      "10 questions de culture generale",
      "Reponds le plus vite possible pour marquer plus de points",
      "Chaque bonne reponse = 100 pts (bonus vitesse)",
      "Mauvaise reponse = 0 point, pas de penalite",
      "Le score total determine le classement",
    ],
    component: () => import("@/components/games/speed-quiz/speed-quiz-game"),
  },
  {
    id: "roast-quiz",
    name: "Roast Quiz",
    description: "Quiz de culture G avec malus visuels a infliger a tes adversaires !",
    category: "trivia",
    minPlayers: 2,
    maxPlayers: 8,
    icon: "🔥",
    implemented: true,
    rules: [
      "10 questions de culture generale, 4 choix, 12s par question",
      "Bonne reponse = +100 pts + tu choisis un malus pour un adversaire",
      "Malus possibles : ecran qui tremble, flou, touches inversees, timer reduit",
      "Le malus s'applique pendant la prochaine question de ta victime",
      "Plus haut score gagne !",
    ],
    component: () => import("@/components/games/roast-quiz/roast-quiz-game"),
  },
  // -- Rapidite --
  {
    id: "reaction-time",
    name: "Reflexes",
    description: "Clique le plus vite possible quand l'ecran change de couleur !",
    category: "speed",
    minPlayers: 2,
    maxPlayers: 8,
    icon: "🎯",
    implemented: true,
    rules: [
      "5 manches de reflexes",
      "Ecran rouge = ATTENDS ! Ne clique pas",
      "Ecran vert = CLIQUE le plus vite possible !",
      "Clic trop tot = +500ms de penalite",
      "Meilleur temps par manche = 100 pts, 2eme = 75, etc.",
    ],
    component: () => import("@/components/games/reaction-time/reaction-time-game"),
  },
  {
    id: "split-second",
    name: "Split Second",
    description: "Micro-defis de 3 secondes - survie WarioWare entre potes !",
    category: "speed",
    minPlayers: 2,
    maxPlayers: 8,
    icon: "⏱️",
    implemented: true,
    rules: [
      "Des micro-defis ultra-rapides (3 secondes !)",
      "Defis varies : clique la bonne couleur, tape un mot, calcule, ne clique pas...",
      "Echouer = perdre 1 vie (3 vies au depart)",
      "Le timer raccourcit a chaque tour",
      "Dernier survivant gagne !",
    ],
    component: () => import("@/components/games/split-second/split-second-game"),
  },
  {
    id: "king-hill",
    name: "King of the Hill",
    description: "Reste sur la colline pour gagner des points - les autres essaient de t'ejecter !",
    category: "speed",
    minPlayers: 2,
    maxPlayers: 8,
    icon: "👑",
    implemented: true,
    rules: [
      "Monte sur la colline pour devenir Roi et gagner 5 pts/seconde",
      "Les autres recoivent des items : Bombe, Grappin, Flashbang, Bouclier",
      "Attaque le Roi - il a quelques secondes pour esquiver !",
      "Plus tu restes Roi longtemps, plus ta fenetre d'esquive retrecit",
      "Partie de 90 secondes - plus haut score gagne !",
    ],
    component: () => import("@/components/games/king-hill/king-hill-game"),
  },
  // -- Bluff / Social --
  {
    id: "loup-garou",
    name: "Loup-Garou",
    description: "Trouve les loups-garous avant qu'ils ne devorent le village !",
    category: "social",
    minPlayers: 4,
    maxPlayers: 8,
    icon: "🐺",
    implemented: true,
    rules: [
      "Roles secrets : Villageois, Loup-Garou, Voyante, Sorciere, Chasseur",
      "La nuit : les Loups eliminent un joueur, la Voyante espionne, la Sorciere peut sauver ou tuer",
      "Le jour : debat et vote pour eliminer un suspect",
      "Villageois gagnent si tous les Loups sont elimines",
      "Loups gagnent s'ils sont en majorite",
    ],
    component: () => import("@/components/games/loup-garou/loup-garou-game"),
  },
  {
    id: "undercover",
    name: "Undercover",
    description: "Decouvre qui a le mot different parmi les joueurs !",
    category: "social",
    minPlayers: 1,
    maxPlayers: 8,
    icon: "🕶️",
    implemented: true,
    rules: [
      "Chaque joueur recoit un mot - certains ont un mot legerement different",
      "A tour de role, donne un indice sur ton mot (sans le dire !)",
      "Apres les indices, votez pour eliminer l'Undercover",
      "Mr. White n'a aucun mot et doit deviner celui des civils",
      "Civils gagnent si l'Undercover est elimine",
    ],
    component: () => import("@/components/games/undercover/undercover-game"),
  },
  {
    id: "infiltre",
    name: "L'Infiltre",
    description: "Un joueur ne connait pas le mot secret... trouve-le !",
    category: "social",
    minPlayers: 3,
    maxPlayers: 8,
    icon: "🕵️",
    implemented: true,
    rules: [
      "Un mot secret est donne a tous... sauf a l'Infiltre !",
      "Chaque joueur donne un indice lie au mot (sans trop en dire)",
      "L'Infiltre doit bluffer et sembler connaitre le mot",
      "Votez pour l'Infiltre - s'il est trouve, il peut tenter de deviner le mot",
      "L'Infiltre gagne s'il n'est pas trouve ou s'il devine le mot",
    ],
    component: () => import("@/components/games/infiltre/infiltre-game"),
  },
  {
    id: "la-taupe",
    name: "La Taupe",
    description: "Cooperez pour reussir les missions - mais la Taupe sabote en secret !",
    category: "social",
    minPlayers: 3,
    maxPlayers: 8,
    icon: "🐀",
    implemented: true,
    rules: [
      "Un joueur est secretement la Taupe, les autres sont Loyaux",
      "5 missions cooperatives : estimation, vote unanime, confiance",
      "La Taupe sabote discretement les efforts du groupe",
      "Apres chaque mission, votez pour identifier la Taupe",
      "Loyaux gagnent si la Taupe est demasquee, la Taupe gagne si elle survit 5 manches",
    ],
    component: () => import("@/components/games/la-taupe/la-taupe-game"),
  },
  {
    id: "black-market",
    name: "Black Market",
    description: "Vends, bluffe et inspecte dans ce marche noir impitoyable !",
    category: "social",
    minPlayers: 3,
    maxPlayers: 8,
    icon: "🏴‍☠️",
    implemented: true,
    rules: [
      "Chaque vendeur pioche 3 cartes (Diamant, Or, Contrefacon, Bombe...)",
      "Le vendeur choisit une carte et declare ce que c'est (il peut mentir !)",
      "Les acheteurs peuvent : Acheter, Inspecter (verifier la verite), ou Passer",
      "Si le vendeur ment et est inspecte -> amende ! S'il dit vrai et est inspecte -> l'inspecteur paye",
      "10 rounds - le plus riche gagne !",
    ],
    component: () => import("@/components/games/black-market/black-market-game"),
  },
  // -- Strategie --
  {
    id: "code-names",
    name: "Noms de Code",
    description: "Donne des indices a ton equipe pour trouver les bons mots sur la grille !",
    category: "strategy",
    minPlayers: 4,
    maxPlayers: 8,
    icon: "🔍",
    implemented: true,
    rules: [
      "2 equipes avec un Espion-maitre chacune",
      "Grille de 25 mots : certains sont a votre equipe, d'autres a l'adversaire",
      "L'Espion donne un indice (1 mot + nombre de mots lies)",
      "L'equipe clique sur les mots qu'elle pense correspondre",
      "Attention a l'Assassin - le toucher = defaite immediate !",
    ],
    component: () => import("@/components/games/code-names/code-names-game"),
  },
  {
    id: "enchere",
    name: "L'Enchere de l'Ombre",
    description: "Encherissez sur des objets mysterieux - certains cachent des malus !",
    category: "strategy",
    minPlayers: 2,
    maxPlayers: 8,
    icon: "🏛️",
    implemented: true,
    rules: [
      "10 objets mis aux encheres, chacun avec une valeur cachee (bonus ou malus !)",
      "Enchere a l'aveugle : tous misent simultanement",
      "Le plus offrant remporte l'objet et paye sa mise",
      "Le 2eme plus offrant peut payer 50 pour empoisonner l'objet (valeur divisee par 2)",
      "Score final = or restant + valeur des objets collectes",
    ],
    component: () => import("@/components/games/enchere/enchere-game"),
  },
  {
    id: "roulette",
    name: "Roulette Russe",
    description: "Parie, bluffe et survie dans cette roulette russe a points !",
    category: "strategy",
    minPlayers: 2,
    maxPlayers: 8,
    icon: "🔫",
    implemented: true,
    rules: [
      "Barillet de 6 chambres avec 1 balle - chaque tour, un joueur tire",
      "Les autres parient sur le resultat : Bang ou Safe",
      "Actions speciales : Sauter (100 pts), Ajouter une balle (150 pts), Verifier (75 pts)",
      "Touche = -300 pts, le barillet se recharge. Safe = une chambre en moins",
      "Paris corrects = x2 la mise. Le plus riche apres 20 tours gagne !",
    ],
    component: () => import("@/components/games/roulette/roulette-game"),
  },
  {
    id: "chess",
    name: "Echecs",
    description: "Joue aux echecs en duel, contre un bot, ou en local sur un seul telephone.",
    category: "strategy",
    minPlayers: 1,
    maxPlayers: 2,
    icon: "♟️",
    implemented: true,
    rules: [
      "Mode en ligne: duel 1v1.",
      "Mode bot: choisis le niveau (facile, moyen, difficile).",
      "Mode local: deux joueurs sur un seul telephone.",
      "Les coups illegaux sont bloques.",
      "Promotion automatique en dame.",
    ],
    component: () => import("@/components/games/chess/chess-game"),
  },
  {
    id: "block-runner",
    name: "Bloc Runner",
    description: "Coop horizontal: avance, saute, ecrase les ennemis et passe tous les niveaux.",
    category: "party",
    minPlayers: 1,
    maxPlayers: 5,
    icon: "🧱",
    implemented: true,
    rules: [
      "Choisis de 1 a 5 joueurs au debut.",
      "Chaque bloc ne peut avancer que vers la droite et sauter.",
      "Ecrase les ennemis par dessus pour les eliminer.",
      "Evite les pieges: si un joueur meurt, le niveau recommence.",
      "Finis tous les niveaux pour gagner.",
    ],
    component: () => import("@/components/games/block-runner/block-runner-game"),
  },
  // -- Cartes --
  {
    id: "uno",
    name: "Uno",
    description: "Sois le premier a vider ta main dans cette bataille de cartes colorees !",
    category: "cards",
    minPlayers: 2,
    maxPlayers: 8,
    icon: "🃏",
    implemented: true,
    rules: [
      "Joue une carte de meme couleur ou meme numero que la carte du dessus",
      "Cartes speciales : +2, Inversion, Passe, Joker, +4",
      "Si tu ne peux pas jouer, pioche une carte",
      "Quand il te reste 1 carte, crie UNO ! (clique le bouton)",
      "Premier a vider sa main gagne !",
    ],
    component: () => import("@/components/games/uno/uno-game"),
  },
  {
    id: "poker",
    name: "Poker",
    description: "Bluffe et mise pour remporter le pot au Texas Hold'em !",
    category: "cards",
    minPlayers: 2,
    maxPlayers: 8,
    icon: "♠️",
    implemented: true,
    rules: [
      "Texas Hold'em : 2 cartes privees + 5 cartes communes",
      "Tours de mise : Preflop -> Flop (3 cartes) -> Turn -> River",
      "Actions : Checker, Miser, Suivre, Relancer, Se coucher",
      "La meilleure main de 5 cartes remporte le pot",
      "Combinaisons : Quinte Flush Royale > Carre > Full > Couleur > Suite > etc.",
    ],
    component: () => import("@/components/games/poker/poker-game"),
  },
  // -- Party / Chaos --
  {
    id: "blind-control",
    name: "Blind Control",
    description: "Tout le monde controle le meme personnage - chaos garanti !",
    category: "party",
    minPlayers: 2,
    maxPlayers: 8,
    icon: "🎮",
    implemented: true,
    rules: [
      "Chaque joueur controle UNE direction du personnage",
      "Guidez ensemble le personnage vers l'objectif sur la grille",
      "Si plusieurs directions sont pressees en meme temps -> conflit, pas de mouvement !",
      "Attention aux pieges qui renvoient au depart",
      "5 niveaux de difficulte croissante - score d'equipe + score personnel",
    ],
    component: () => import("@/components/games/blind-control/blind-control-game"),
  },
  // -- Sport --
  {
    id: "motion-tennis",
    name: "Motion Tennis",
    description: "Tennis 3D facon Wii Sports - ton telephone est ta raquette !",
    category: "sport",
    minPlayers: 1,
    maxPlayers: 2,
    icon: "🎾",
    implemented: true,
    rules: [
      "Doubles Wii Sports : 4 persos sur le terrain, tu controles les 2 de ton cote",
      "Scanne le QR code avec ton telephone pour l'utiliser comme raquette",
      "Tiens ton telephone comme une raquette et swing pour servir et frapper",
      "Coup droit, revers, smash, slice et lob detectes automatiquement",
      "Le perso le plus proche de la balle frappe quand tu swing",
      "Premier a 7 points - service alterne tous les 2 points",
    ],
    component: () => import("@/components/games/motion-tennis/motion-tennis-game"),
  },
];

export function getGameById(id: string): GameMeta | undefined {
  return GAMES.find((g) => g.id === id);
}

export function getGamesByCategory(category: string): GameMeta[] {
  return GAMES.filter((g) => g.category === category);
}

export const CATEGORIES = [
  { id: "all", label: "Tous" },
  { id: "words", label: "Mots" },
  { id: "trivia", label: "Culture" },
  { id: "speed", label: "Rapidite" },
  { id: "strategy", label: "Strategie" },
  { id: "social", label: "Bluff" },
  { id: "cards", label: "Cartes" },
  { id: "party", label: "Party" },
  { id: "sport", label: "Sport" },
] as const;
