import type { GameMeta } from "./types";

export const GAMES: GameMeta[] = [
  // ── Mots ──────────────────────────────
  {
    id: "bomb-party",
    name: "Bomb Party",
    description: "Trouve un mot contenant la syllabe imposée avant que la bombe explose !",
    category: "words",
    minPlayers: 2,
    maxPlayers: 8,
    icon: "💣",
    implemented: true,
    rules: [
      "Une syllabe est imposée à chaque tour",
      "Tape un mot contenant cette syllabe avant que le timer explose",
      "Chaque mot ne peut être utilisé qu'une seule fois",
      "Tu perds une vie si le temps expire",
      "Le dernier survivant gagne !",
    ],
    component: () => import("@/components/games/bomb-party/bomb-party-game"),
  },
  {
    id: "word-chain",
    name: "Chaîne de mots",
    description: "Chaque joueur doit dire un mot commençant par la dernière lettre du mot précédent.",
    category: "words",
    minPlayers: 2,
    maxPlayers: 8,
    icon: "🔗",
    implemented: true,
    rules: [
      "Dis un mot commençant par la dernière lettre du mot précédent",
      "Le mot doit faire au moins 3 lettres",
      "Les mots déjà utilisés sont interdits",
      "Tu as 8 secondes par tour (diminue progressivement)",
      "3 vies — le dernier debout gagne",
    ],
    component: () => import("@/components/games/word-chain/word-chain-game"),
  },
  // ── Culture ───────────────────────────
  {
    id: "speed-quiz",
    name: "Speed Quiz",
    description: "Réponds le plus vite possible aux questions de culture générale !",
    category: "trivia",
    minPlayers: 2,
    maxPlayers: 8,
    icon: "⚡",
    implemented: true,
    rules: [
      "10 questions de culture générale",
      "Réponds le plus vite possible pour marquer plus de points",
      "Chaque bonne réponse = 100 pts (bonus vitesse)",
      "Mauvaise réponse = 0 point, pas de pénalité",
      "Le score total détermine le classement",
    ],
    component: () => import("@/components/games/speed-quiz/speed-quiz-game"),
  },
  {
    id: "roast-quiz",
    name: "Roast Quiz",
    description: "Quiz de culture G avec malus visuels à infliger à tes adversaires !",
    category: "trivia",
    minPlayers: 2,
    maxPlayers: 8,
    icon: "🔥",
    implemented: true,
    rules: [
      "10 questions de culture générale, 4 choix, 12s par question",
      "Bonne réponse = +100 pts + tu choisis un malus pour un adversaire",
      "Malus possibles : écran qui tremble, flou, touches inversées, timer réduit",
      "Le malus s'applique pendant la prochaine question de ta victime",
      "Plus haut score gagne !",
    ],
    component: () => import("@/components/games/roast-quiz/roast-quiz-game"),
  },
  // ── Rapidité ──────────────────────────
  {
    id: "reaction-time",
    name: "Réflexes",
    description: "Clique le plus vite possible quand l'écran change de couleur !",
    category: "speed",
    minPlayers: 2,
    maxPlayers: 8,
    icon: "🎯",
    implemented: true,
    rules: [
      "5 manches de réflexes",
      "Écran rouge = ATTENDS ! Ne clique pas",
      "Écran vert = CLIQUE le plus vite possible !",
      "Clic trop tôt = +500ms de pénalité",
      "Meilleur temps par manche = 100 pts, 2ème = 75, etc.",
    ],
    component: () => import("@/components/games/reaction-time/reaction-time-game"),
  },
  {
    id: "split-second",
    name: "Split Second",
    description: "Micro-défis de 3 secondes — survie WarioWare entre potes !",
    category: "speed",
    minPlayers: 2,
    maxPlayers: 8,
    icon: "⏱️",
    implemented: true,
    rules: [
      "Des micro-défis ultra-rapides (3 secondes !)",
      "Défis variés : clique la bonne couleur, tape un mot, calcule, ne clique pas...",
      "Échouer = perdre 1 vie (3 vies au départ)",
      "Le timer raccourcit à chaque tour",
      "Dernier survivant gagne !",
    ],
    component: () => import("@/components/games/split-second/split-second-game"),
  },
  {
    id: "king-hill",
    name: "King of the Hill",
    description: "Reste sur la colline pour gagner des points — les autres essaient de t'éjecter !",
    category: "speed",
    minPlayers: 2,
    maxPlayers: 8,
    icon: "👑",
    implemented: true,
    rules: [
      "Monte sur la colline pour devenir Roi et gagner 5 pts/seconde",
      "Les autres reçoivent des items : Bombe 💣, Grappin 🪝, Flashbang ⚡, Bouclier 🛡️",
      "Attaque le Roi — il a quelques secondes pour esquiver !",
      "Plus tu restes Roi longtemps, plus ta fenêtre d'esquive rétrécit",
      "Partie de 90 secondes — plus haut score gagne !",
    ],
    component: () => import("@/components/games/king-hill/king-hill-game"),
  },
  // ── Bluff / Social ────────────────────
  {
    id: "loup-garou",
    name: "Loup-Garou",
    description: "Trouve les loups-garous avant qu'ils ne dévorent le village !",
    category: "social",
    minPlayers: 4,
    maxPlayers: 8,
    icon: "🐺",
    implemented: true,
    rules: [
      "Rôles secrets : Villageois, Loup-Garou, Voyante, Sorcière, Chasseur",
      "La nuit : les Loups éliminent un joueur, la Voyante espionne, la Sorcière peut sauver ou tuer",
      "Le jour : débat et vote pour éliminer un suspect",
      "Villageois gagnent si tous les Loups sont éliminés",
      "Loups gagnent s'ils sont en majorité",
    ],
    component: () => import("@/components/games/loup-garou/loup-garou-game"),
  },
  {
    id: "undercover",
    name: "Undercover",
    description: "Découvre qui a le mot différent parmi les joueurs !",
    category: "social",
    minPlayers: 3,
    maxPlayers: 8,
    icon: "🕶️",
    implemented: true,
    rules: [
      "Chaque joueur reçoit un mot — certains ont un mot légèrement différent",
      "À tour de rôle, donne un indice sur ton mot (sans le dire !)",
      "Après les indices, votez pour éliminer l'Undercover",
      "Mr. White n'a aucun mot et doit deviner celui des civils",
      "Civils gagnent si l'Undercover est éliminé",
    ],
    component: () => import("@/components/games/undercover/undercover-game"),
  },
  {
    id: "infiltre",
    name: "L'Infiltré",
    description: "Un joueur ne connaît pas le mot secret... trouve-le !",
    category: "social",
    minPlayers: 3,
    maxPlayers: 8,
    icon: "🕵️",
    implemented: true,
    rules: [
      "Un mot secret est donné à tous... sauf à l'Infiltré !",
      "Chaque joueur donne un indice lié au mot (sans trop en dire)",
      "L'Infiltré doit bluffer et sembler connaître le mot",
      "Votez pour l'Infiltré — s'il est trouvé, il peut tenter de deviner le mot",
      "L'Infiltré gagne s'il n'est pas trouvé ou s'il devine le mot",
    ],
    component: () => import("@/components/games/infiltre/infiltre-game"),
  },
  {
    id: "la-taupe",
    name: "La Taupe",
    description: "Coopérez pour réussir les missions — mais la Taupe sabote en secret !",
    category: "social",
    minPlayers: 3,
    maxPlayers: 8,
    icon: "🐀",
    implemented: true,
    rules: [
      "Un joueur est secrètement la Taupe, les autres sont Loyaux",
      "5 missions coopératives : estimation, vote unanime, confiance",
      "La Taupe sabote discrètement les efforts du groupe",
      "Après chaque mission, votez pour identifier la Taupe",
      "Loyaux gagnent si la Taupe est démasquée, la Taupe gagne si elle survit 5 manches",
    ],
    component: () => import("@/components/games/la-taupe/la-taupe-game"),
  },
  {
    id: "black-market",
    name: "Black Market",
    description: "Vends, bluffe et inspecte dans ce marché noir impitoyable !",
    category: "social",
    minPlayers: 3,
    maxPlayers: 8,
    icon: "🏴‍☠️",
    implemented: true,
    rules: [
      "Chaque vendeur pioche 3 cartes (Diamant, Or, Contrefaçon, Bombe...)",
      "Le vendeur choisit une carte et déclare ce que c'est (il peut mentir !)",
      "Les acheteurs peuvent : Acheter, Inspecter (vérifier la vérité), ou Passer",
      "Si le vendeur ment et est inspecté → amende ! S'il dit vrai et est inspecté → l'inspecteur paye",
      "10 rounds — le plus riche gagne !",
    ],
    component: () => import("@/components/games/black-market/black-market-game"),
  },
  // ── Stratégie ─────────────────────────
  {
    id: "code-names",
    name: "Noms de Code",
    description: "Donne des indices à ton équipe pour trouver les bons mots sur la grille !",
    category: "strategy",
    minPlayers: 4,
    maxPlayers: 8,
    icon: "🔍",
    implemented: true,
    rules: [
      "2 équipes avec un Espion-maître chacune",
      "Grille de 25 mots : certains sont à votre équipe, d'autres à l'adversaire",
      "L'Espion donne un indice (1 mot + nombre de mots liés)",
      "L'équipe clique sur les mots qu'elle pense correspondre",
      "Attention à l'Assassin — le toucher = défaite immédiate !",
    ],
    component: () => import("@/components/games/code-names/code-names-game"),
  },
  {
    id: "enchere",
    name: "L'Enchère de l'Ombre",
    description: "Enchérissez sur des objets mystérieux — certains cachent des malus !",
    category: "strategy",
    minPlayers: 2,
    maxPlayers: 8,
    icon: "🏛️",
    implemented: true,
    rules: [
      "10 objets mis aux enchères, chacun avec une valeur cachée (bonus ou malus !)",
      "Enchère à l'aveugle : tous misent simultanément",
      "Le plus offrant remporte l'objet et paye sa mise",
      "Le 2ème plus offrant peut payer 50🪙 pour empoisonner l'objet (valeur divisée par 2)",
      "Score final = or restant + valeur des objets collectés",
    ],
    component: () => import("@/components/games/enchere/enchere-game"),
  },
  {
    id: "roulette",
    name: "Roulette Russe",
    description: "Parie, bluffe et survie dans cette roulette russe à points !",
    category: "strategy",
    minPlayers: 2,
    maxPlayers: 8,
    icon: "🔫",
    implemented: true,
    rules: [
      "Barillet de 6 chambres avec 1 balle — chaque tour, un joueur tire",
      "Les autres parient sur le résultat : Bang ou Safe",
      "Actions spéciales : Sauter (100 pts), Ajouter une balle (150 pts), Vérifier (75 pts)",
      "Touché = -300 pts, le barillet se recharge. Safe = une chambre en moins",
      "Paris corrects = x2 la mise. Le plus riche après 20 tours gagne !",
    ],
    component: () => import("@/components/games/roulette/roulette-game"),
  },
  // ── Cartes ────────────────────────────
  {
    id: "uno",
    name: "Uno",
    description: "Sois le premier à vider ta main dans cette bataille de cartes colorées !",
    category: "cards",
    minPlayers: 2,
    maxPlayers: 8,
    icon: "🃏",
    implemented: true,
    rules: [
      "Joue une carte de même couleur ou même numéro que la carte du dessus",
      "Cartes spéciales : +2, Inversion, Passe, Joker, +4",
      "Si tu ne peux pas jouer, pioche une carte",
      "Quand il te reste 1 carte, crie UNO ! (clique le bouton)",
      "Premier à vider sa main gagne !",
    ],
    component: () => import("@/components/games/uno/uno-game"),
  },
  {
    id: "poker",
    name: "Poker",
    description: "Bluffe et mise pour remporter le pot au Texas Hold'em !",
    category: "cards",
    minPlayers: 2,
    maxPlayers: 8,
    icon: "♠️",
    implemented: true,
    rules: [
      "Texas Hold'em : 2 cartes privées + 5 cartes communes",
      "Tours de mise : Preflop → Flop (3 cartes) → Turn → River",
      "Actions : Checker, Miser, Suivre, Relancer, Se coucher",
      "La meilleure main de 5 cartes remporte le pot",
      "Combinaisons : Quinte Flush Royale > Carré > Full > Couleur > Suite > etc.",
    ],
    component: () => import("@/components/games/poker/poker-game"),
  },
  // ── Party / Chaos ─────────────────────
  {
    id: "blind-control",
    name: "Blind Control",
    description: "Tout le monde contrôle le même personnage — chaos garanti !",
    category: "party",
    minPlayers: 2,
    maxPlayers: 8,
    icon: "🎮",
    implemented: true,
    rules: [
      "Chaque joueur contrôle UNE direction du personnage (⬆️⬇️⬅️➡️)",
      "Guidez ensemble le personnage vers l'objectif sur la grille",
      "Si plusieurs directions sont pressées en même temps → conflit, pas de mouvement !",
      "Attention aux pièges qui renvoient au départ",
      "5 niveaux de difficulté croissante — score d'équipe + score personnel",
    ],
    component: () => import("@/components/games/blind-control/blind-control-game"),
  },
  // ── Sport ──────────────────────────────
  {
    id: "motion-tennis",
    name: "Motion Tennis",
    description: "Tennis 3D façon Wii Sports — ton téléphone est ta raquette !",
    category: "sport",
    minPlayers: 1,
    maxPlayers: 2,
    icon: "🎾",
    implemented: true,
    rules: [
      "Doubles Wii Sports : 4 persos sur le terrain, tu contrôles les 2 de ton côté",
      "Scanne le QR code avec ton téléphone pour l'utiliser comme raquette",
      "Tiens ton téléphone comme une raquette et swing pour servir et frapper",
      "Coup droit, revers, smash, slice et lob détectés automatiquement",
      "Le perso le plus proche de la balle frappe quand tu swing",
      "Premier à 7 points — service alterne tous les 2 points",
    ],
    component: () => import("@/components/games/motion-tennis/motion-tennis-game"),
  },
];

export function getGameById(id: string): GameMeta | undefined {
  return GAMES.find((g) => g.id === id);
}

export function getGamesByCategory(category: string): GameMeta[] {
  return GAMES.filter((g) => g.category === category);
}

export const CATEGORIES = [
  { id: "all", label: "Tous" },
  { id: "words", label: "Mots" },
  { id: "trivia", label: "Culture" },
  { id: "speed", label: "Rapidité" },
  { id: "strategy", label: "Stratégie" },
  { id: "social", label: "Bluff" },
  { id: "cards", label: "Cartes" },
  { id: "party", label: "Party" },
  { id: "sport", label: "Sport" },
] as const;
