import type { GameMeta } from "./types";

export const GAMES: GameMeta[] = [
  // â”€â”€ Mots â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    id: "bomb-party",
    name: "Bomb Party",
    description: "Trouve un mot contenant la syllabe imposÃ©e avant que la bombe explose !",
    category: "words",
    minPlayers: 2,
    maxPlayers: 8,
    icon: "ðŸ’£",
    implemented: true,
    rules: [
      "Une syllabe est imposÃ©e Ã  chaque tour",
      "Tape un mot contenant cette syllabe avant que le timer explose",
      "Chaque mot ne peut Ãªtre utilisÃ© qu'une seule fois",
      "Tu perds une vie si le temps expire",
      "Le dernier survivant gagne !",
    ],
    component: () => import("@/components/games/bomb-party/bomb-party-game"),
  },
  {
    id: "word-chain",
    name: "ChaÃ®ne de mots",
    description: "Chaque joueur doit dire un mot commenÃ§ant par la derniÃ¨re lettre du mot prÃ©cÃ©dent.",
    category: "words",
    minPlayers: 2,
    maxPlayers: 8,
    icon: "ðŸ”—",
    implemented: true,
    rules: [
      "Dis un mot commenÃ§ant par la derniÃ¨re lettre du mot prÃ©cÃ©dent",
      "Le mot doit faire au moins 3 lettres",
      "Les mots dÃ©jÃ  utilisÃ©s sont interdits",
      "Tu as 8 secondes par tour (diminue progressivement)",
      "3 vies â€” le dernier debout gagne",
    ],
    component: () => import("@/components/games/word-chain/word-chain-game"),
  },
  // â”€â”€ Culture â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    id: "speed-quiz",
    name: "Speed Quiz",
    description: "RÃ©ponds le plus vite possible aux questions de culture gÃ©nÃ©rale !",
    category: "trivia",
    minPlayers: 2,
    maxPlayers: 8,
    icon: "âš¡",
    implemented: true,
    rules: [
      "10 questions de culture gÃ©nÃ©rale",
      "RÃ©ponds le plus vite possible pour marquer plus de points",
      "Chaque bonne rÃ©ponse = 100 pts (bonus vitesse)",
      "Mauvaise rÃ©ponse = 0 point, pas de pÃ©nalitÃ©",
      "Le score total dÃ©termine le classement",
    ],
    component: () => import("@/components/games/speed-quiz/speed-quiz-game"),
  },
  {
    id: "roast-quiz",
    name: "Roast Quiz",
    description: "Quiz de culture G avec malus visuels Ã  infliger Ã  tes adversaires !",
    category: "trivia",
    minPlayers: 2,
    maxPlayers: 8,
    icon: "ðŸ”¥",
    implemented: true,
    rules: [
      "10 questions de culture gÃ©nÃ©rale, 4 choix, 12s par question",
      "Bonne rÃ©ponse = +100 pts + tu choisis un malus pour un adversaire",
      "Malus possibles : Ã©cran qui tremble, flou, touches inversÃ©es, timer rÃ©duit",
      "Le malus s'applique pendant la prochaine question de ta victime",
      "Plus haut score gagne !",
    ],
    component: () => import("@/components/games/roast-quiz/roast-quiz-game"),
  },
  // â”€â”€ RapiditÃ© â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    id: "reaction-time",
    name: "RÃ©flexes",
    description: "Clique le plus vite possible quand l'Ã©cran change de couleur !",
    category: "speed",
    minPlayers: 2,
    maxPlayers: 8,
    icon: "ðŸŽ¯",
    implemented: true,
    rules: [
      "5 manches de rÃ©flexes",
      "Ã‰cran rouge = ATTENDS ! Ne clique pas",
      "Ã‰cran vert = CLIQUE le plus vite possible !",
      "Clic trop tÃ´t = +500ms de pÃ©nalitÃ©",
      "Meilleur temps par manche = 100 pts, 2Ã¨me = 75, etc.",
    ],
    component: () => import("@/components/games/reaction-time/reaction-time-game"),
  },
  {
    id: "split-second",
    name: "Split Second",
    description: "Micro-dÃ©fis de 3 secondes â€” survie WarioWare entre potes !",
    category: "speed",
    minPlayers: 2,
    maxPlayers: 8,
    icon: "â±ï¸",
    implemented: true,
    rules: [
      "Des micro-dÃ©fis ultra-rapides (3 secondes !)",
      "DÃ©fis variÃ©s : clique la bonne couleur, tape un mot, calcule, ne clique pas...",
      "Ã‰chouer = perdre 1 vie (3 vies au dÃ©part)",
      "Le timer raccourcit Ã  chaque tour",
      "Dernier survivant gagne !",
    ],
    component: () => import("@/components/games/split-second/split-second-game"),
  },
  {
    id: "king-hill",
    name: "King of the Hill",
    description: "Reste sur la colline pour gagner des points â€” les autres essaient de t'Ã©jecter !",
    category: "speed",
    minPlayers: 2,
    maxPlayers: 8,
    icon: "ðŸ‘‘",
    implemented: true,
    rules: [
      "Monte sur la colline pour devenir Roi et gagner 5 pts/seconde",
      "Les autres reÃ§oivent des items : Bombe ðŸ’£, Grappin ðŸª, Flashbang âš¡, Bouclier ðŸ›¡ï¸",
      "Attaque le Roi â€” il a quelques secondes pour esquiver !",
      "Plus tu restes Roi longtemps, plus ta fenÃªtre d'esquive rÃ©trÃ©cit",
      "Partie de 90 secondes â€” plus haut score gagne !",
    ],
    component: () => import("@/components/games/king-hill/king-hill-game"),
  },
  // â”€â”€ Bluff / Social â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    id: "loup-garou",
    name: "Loup-Garou",
    description: "Trouve les loups-garous avant qu'ils ne dÃ©vorent le village !",
    category: "social",
    minPlayers: 4,
    maxPlayers: 8,
    icon: "ðŸº",
    implemented: true,
    rules: [
      "RÃ´les secrets : Villageois, Loup-Garou, Voyante, SorciÃ¨re, Chasseur",
      "La nuit : les Loups Ã©liminent un joueur, la Voyante espionne, la SorciÃ¨re peut sauver ou tuer",
      "Le jour : dÃ©bat et vote pour Ã©liminer un suspect",
      "Villageois gagnent si tous les Loups sont Ã©liminÃ©s",
      "Loups gagnent s'ils sont en majoritÃ©",
    ],
    component: () => import("@/components/games/loup-garou/loup-garou-game"),
  },
  {
    id: "undercover",
    name: "Undercover",
    description: "DÃ©couvre qui a le mot diffÃ©rent parmi les joueurs !",
    category: "social",
    minPlayers: 1,
    maxPlayers: 8,
    icon: "ðŸ•¶ï¸",
    implemented: true,
    rules: [
      "Chaque joueur reÃ§oit un mot â€” certains ont un mot lÃ©gÃ¨rement diffÃ©rent",
      "Ã€ tour de rÃ´le, donne un indice sur ton mot (sans le dire !)",
      "AprÃ¨s les indices, votez pour Ã©liminer l'Undercover",
      "Mr. White n'a aucun mot et doit deviner celui des civils",
      "Civils gagnent si l'Undercover est Ã©liminÃ©",
    ],
    component: () => import("@/components/games/undercover/undercover-game"),
  },
  {
    id: "infiltre",
    name: "L'InfiltrÃ©",
    description: "Un joueur ne connaÃ®t pas le mot secret... trouve-le !",
    category: "social",
    minPlayers: 3,
    maxPlayers: 8,
    icon: "ðŸ•µï¸",
    implemented: true,
    rules: [
      "Un mot secret est donnÃ© Ã  tous... sauf Ã  l'InfiltrÃ© !",
      "Chaque joueur donne un indice liÃ© au mot (sans trop en dire)",
      "L'InfiltrÃ© doit bluffer et sembler connaÃ®tre le mot",
      "Votez pour l'InfiltrÃ© â€” s'il est trouvÃ©, il peut tenter de deviner le mot",
      "L'InfiltrÃ© gagne s'il n'est pas trouvÃ© ou s'il devine le mot",
    ],
    component: () => import("@/components/games/infiltre/infiltre-game"),
  },
  {
    id: "la-taupe",
    name: "La Taupe",
    description: "CoopÃ©rez pour rÃ©ussir les missions â€” mais la Taupe sabote en secret !",
    category: "social",
    minPlayers: 3,
    maxPlayers: 8,
    icon: "ðŸ€",
    implemented: true,
    rules: [
      "Un joueur est secrÃ¨tement la Taupe, les autres sont Loyaux",
      "5 missions coopÃ©ratives : estimation, vote unanime, confiance",
      "La Taupe sabote discrÃ¨tement les efforts du groupe",
      "AprÃ¨s chaque mission, votez pour identifier la Taupe",
      "Loyaux gagnent si la Taupe est dÃ©masquÃ©e, la Taupe gagne si elle survit 5 manches",
    ],
    component: () => import("@/components/games/la-taupe/la-taupe-game"),
  },
  {
    id: "black-market",
    name: "Black Market",
    description: "Vends, bluffe et inspecte dans ce marchÃ© noir impitoyable !",
    category: "social",
    minPlayers: 3,
    maxPlayers: 8,
    icon: "ðŸ´â€â˜ ï¸",
    implemented: true,
    rules: [
      "Chaque vendeur pioche 3 cartes (Diamant, Or, ContrefaÃ§on, Bombe...)",
      "Le vendeur choisit une carte et dÃ©clare ce que c'est (il peut mentir !)",
      "Les acheteurs peuvent : Acheter, Inspecter (vÃ©rifier la vÃ©ritÃ©), ou Passer",
      "Si le vendeur ment et est inspectÃ© â†’ amende ! S'il dit vrai et est inspectÃ© â†’ l'inspecteur paye",
      "10 rounds â€” le plus riche gagne !",
    ],
    component: () => import("@/components/games/black-market/black-market-game"),
  },
  // â”€â”€ StratÃ©gie â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    id: "code-names",
    name: "Noms de Code",
    description: "Donne des indices Ã  ton Ã©quipe pour trouver les bons mots sur la grille !",
    category: "strategy",
    minPlayers: 4,
    maxPlayers: 8,
    icon: "ðŸ”",
    implemented: true,
    rules: [
      "2 Ã©quipes avec un Espion-maÃ®tre chacune",
      "Grille de 25 mots : certains sont Ã  votre Ã©quipe, d'autres Ã  l'adversaire",
      "L'Espion donne un indice (1 mot + nombre de mots liÃ©s)",
      "L'Ã©quipe clique sur les mots qu'elle pense correspondre",
      "Attention Ã  l'Assassin â€” le toucher = dÃ©faite immÃ©diate !",
    ],
    component: () => import("@/components/games/code-names/code-names-game"),
  },
  {
    id: "enchere",
    name: "L'EnchÃ¨re de l'Ombre",
    description: "EnchÃ©rissez sur des objets mystÃ©rieux â€” certains cachent des malus !",
    category: "strategy",
    minPlayers: 2,
    maxPlayers: 8,
    icon: "ðŸ›ï¸",
    implemented: true,
    rules: [
      "10 objets mis aux enchÃ¨res, chacun avec une valeur cachÃ©e (bonus ou malus !)",
      "EnchÃ¨re Ã  l'aveugle : tous misent simultanÃ©ment",
      "Le plus offrant remporte l'objet et paye sa mise",
      "Le 2Ã¨me plus offrant peut payer 50ðŸª™ pour empoisonner l'objet (valeur divisÃ©e par 2)",
      "Score final = or restant + valeur des objets collectÃ©s",
    ],
    component: () => import("@/components/games/enchere/enchere-game"),
  },
  {
    id: "roulette",
    name: "Roulette Russe",
    description: "Parie, bluffe et survie dans cette roulette russe Ã  points !",
    category: "strategy",
    minPlayers: 2,
    maxPlayers: 8,
    icon: "ðŸ”«",
    implemented: true,
    rules: [
      "Barillet de 6 chambres avec 1 balle â€” chaque tour, un joueur tire",
      "Les autres parient sur le rÃ©sultat : Bang ou Safe",
      "Actions spÃ©ciales : Sauter (100 pts), Ajouter une balle (150 pts), VÃ©rifier (75 pts)",
      "TouchÃ© = -300 pts, le barillet se recharge. Safe = une chambre en moins",
      "Paris corrects = x2 la mise. Le plus riche aprÃ¨s 20 tours gagne !",
    ],
    component: () => import("@/components/games/roulette/roulette-game"),
  },
  {
    id: "chess",
    name: "Echecs",
    description: "Joue aux echecs en duel, contre un bot, ou en local sur un seul telephone.",
    category: "strategy",
    minPlayers: 1,
    maxPlayers: 2,
    icon: "♟️",
    implemented: true,
    rules: [
      "Mode en ligne: duel 1v1.",
      "Mode bot: choisis le niveau (facile, moyen, difficile).",
      "Mode local: deux joueurs sur un seul telephone.",
      "Les coups illegaux sont bloques.",
      "Promotion automatique en dame.",
    ],
    component: () => import("@/components/games/chess/chess-game"),
  },
  // â”€â”€ Cartes â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    id: "uno",
    name: "Uno",
    description: "Sois le premier Ã  vider ta main dans cette bataille de cartes colorÃ©es !",
    category: "cards",
    minPlayers: 2,
    maxPlayers: 8,
    icon: "ðŸƒ",
    implemented: true,
    rules: [
      "Joue une carte de mÃªme couleur ou mÃªme numÃ©ro que la carte du dessus",
      "Cartes spÃ©ciales : +2, Inversion, Passe, Joker, +4",
      "Si tu ne peux pas jouer, pioche une carte",
      "Quand il te reste 1 carte, crie UNO ! (clique le bouton)",
      "Premier Ã  vider sa main gagne !",
    ],
    component: () => import("@/components/games/uno/uno-game"),
  },
  {
    id: "poker",
    name: "Poker",
    description: "Bluffe et mise pour remporter le pot au Texas Hold'em !",
    category: "cards",
    minPlayers: 2,
    maxPlayers: 8,
    icon: "â™ ï¸",
    implemented: true,
    rules: [
      "Texas Hold'em : 2 cartes privÃ©es + 5 cartes communes",
      "Tours de mise : Preflop â†’ Flop (3 cartes) â†’ Turn â†’ River",
      "Actions : Checker, Miser, Suivre, Relancer, Se coucher",
      "La meilleure main de 5 cartes remporte le pot",
      "Combinaisons : Quinte Flush Royale > CarrÃ© > Full > Couleur > Suite > etc.",
    ],
    component: () => import("@/components/games/poker/poker-game"),
  },
  // â”€â”€ Party / Chaos â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    id: "blind-control",
    name: "Blind Control",
    description: "Tout le monde contrÃ´le le mÃªme personnage â€” chaos garanti !",
    category: "party",
    minPlayers: 2,
    maxPlayers: 8,
    icon: "ðŸŽ®",
    implemented: true,
    rules: [
      "Chaque joueur contrÃ´le UNE direction du personnage (â¬†ï¸â¬‡ï¸â¬…ï¸âž¡ï¸)",
      "Guidez ensemble le personnage vers l'objectif sur la grille",
      "Si plusieurs directions sont pressÃ©es en mÃªme temps â†’ conflit, pas de mouvement !",
      "Attention aux piÃ¨ges qui renvoient au dÃ©part",
      "5 niveaux de difficultÃ© croissante â€” score d'Ã©quipe + score personnel",
    ],
    component: () => import("@/components/games/blind-control/blind-control-game"),
  },
  // â”€â”€ Sport â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    id: "motion-tennis",
    name: "Motion Tennis",
    description: "Tennis 3D faÃ§on Wii Sports â€” ton tÃ©lÃ©phone est ta raquette !",
    category: "sport",
    minPlayers: 1,
    maxPlayers: 2,
    icon: "ðŸŽ¾",
    implemented: true,
    rules: [
      "Doubles Wii Sports : 4 persos sur le terrain, tu contrÃ´les les 2 de ton cÃ´tÃ©",
      "Scanne le QR code avec ton tÃ©lÃ©phone pour l'utiliser comme raquette",
      "Tiens ton tÃ©lÃ©phone comme une raquette et swing pour servir et frapper",
      "Coup droit, revers, smash, slice et lob dÃ©tectÃ©s automatiquement",
      "Le perso le plus proche de la balle frappe quand tu swing",
      "Premier Ã  7 points â€” service alterne tous les 2 points",
    ],
    component: () => import("@/components/games/motion-tennis/motion-tennis-game"),
  },
];

export function getGameById(id: string): GameMeta | undefined {
  return GAMES.find((g) => g.id === id);
}

export function getGamesByCategory(category: string): GameMeta[] {
  return GAMES.filter((g) => g.category === category);
}

export const CATEGORIES = [
  { id: "all", label: "Tous" },
  { id: "words", label: "Mots" },
  { id: "trivia", label: "Culture" },
  { id: "speed", label: "RapiditÃ©" },
  { id: "strategy", label: "StratÃ©gie" },
  { id: "social", label: "Bluff" },
  { id: "cards", label: "Cartes" },
  { id: "party", label: "Party" },
  { id: "sport", label: "Sport" },
] as const;
